// Copyright the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command exampledoc writes the testable examples of packages to a Markdown
// file.
//
// Usage:
//
//	exampledoc [-check] [-o file] dir...
//
// Each dir is the directory of a package.  The command reads the example
// functions in the _test.go files of each directory.  For each example, the
// Markdown file shows the doc comment, the complete program, and the output.
// Each example must be in an external test package, such as stdout_test.  An
// example must use only the declarations in its own file.
//
// The -o flag names the Markdown file.  The default is docs/examples.md.
//
// With -check, the command does not write the Markdown file.  The command
// exits with status 1 if the Markdown file is different from the generated
// text.
package main

import (
	"bytes"
	"cmp"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/build"
	"go/doc"
	"go/doc/comment"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"
	"unicode/utf8"
)

// filePerm is the permission of the Markdown file if the command creates it.
const filePerm = 0o600

const header = `<!-- Code generated by exampledoc. DO NOT EDIT. -->

# gslog Examples

This file shows each testable example of the gslog packages as a complete
program. ` + "`go test`" + ` runs each example that shows an output. Then it
compares the output of the example with the output below the program. Run
` + "`make docs`" + ` to update this file.
`

func main() {
	log.SetFlags(0)
	log.SetPrefix("exampledoc: ")

	err := run()
	if err != nil {
		log.Fatal(err)
	}
}

// run parses the command line, and then writes or compares the Markdown
// file.
func run() error {
	out := flag.String("o", "docs/examples.md", "the Markdown file")
	check := flag.Bool("check", false, "compare the file with the generated text, and do not write it")

	flag.Parse()

	text, err := render(flag.Args())
	if err != nil {
		return err
	}

	if *check {
		return compare(*out, text)
	}

	return os.WriteFile(*out, text, filePerm)
}

// render returns the Markdown text for the packages in dirs.
func render(dirs []string) ([]byte, error) {
	if len(dirs) == 0 {
		return nil, errors.New("no package directories")
	}

	module, err := modulePath("go.mod")
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer

	buf.WriteString(header)

	for _, dir := range dirs {
		err = renderPackage(&buf, module, dir)
		if err != nil {
			return nil, err
		}
	}

	return buf.Bytes(), nil
}

// renderPackage writes the package doc comment and the examples of the
// package in dir to buf.  The examples are in order of file name, and then
// in source order.
func renderPackage(buf *bytes.Buffer, module, dir string) error {
	fset := token.NewFileSet()

	name, pkgDoc, tests, err := parseDir(fset, dir)
	if err != nil {
		return err
	}

	examples := doc.Examples(tests...)
	if len(examples) == 0 {
		return fmt.Errorf("%s: no examples", dir)
	}

	slices.SortFunc(examples, func(a, b *doc.Example) int {
		return cmp.Compare(a.Code.Pos(), b.Code.Pos())
	})

	importPath := module + "/" + filepath.ToSlash(filepath.Clean(dir))
	synopsis := markdown(pkgDoc)

	fmt.Fprintf(buf, "\n## %s\n\n%s", importPath, synopsis)

	for _, ex := range examples {
		err = renderExample(buf, fset, name, ex)
		if err != nil {
			return fmt.Errorf("%s: %w", dir, err)
		}
	}

	return nil
}

// renderExample writes the title, the doc comment, the complete program, and
// the output of ex to buf.
func renderExample(buf *bytes.Buffer, fset *token.FileSet, pkg string, ex *doc.Example) error {
	if ex.Play == nil {
		return fmt.Errorf("example %s is not a complete program: "+
			"it must be in an external test package and use only the declarations in its own file", ex.Name)
	}

	var program bytes.Buffer

	err := format.Node(&program, fset, ex.Play)
	if err != nil {
		return fmt.Errorf("example %s: %w", ex.Name, err)
	}

	heading := title(pkg, ex)

	fmt.Fprintf(buf, "\n### %s\n\n", heading)

	if ex.Doc != "" {
		description := markdown(ex.Doc)

		fmt.Fprintf(buf, "%s\n", description)
	}

	fmt.Fprintf(buf, "```go\n%s```\n", program.Bytes())

	if ex.Output != "" {
		label := "Output"
		if ex.Unordered {
			label = "Output, in any order"
		}

		fmt.Fprintf(buf, "\n%s:\n\n```text\n%s```\n", label, ex.Output)
	}

	return nil
}

// parseDir parses the Go files in dir that match the build context.
// parseDir returns the package name and the package doc comment from the
// non-test files, and the parsed test files.
func parseDir(fset *token.FileSet, dir string) (name, pkgDoc string, tests []*ast.File, err error) {
	pkg, err := build.ImportDir(dir, 0)
	if err != nil {
		return "", "", nil, err
	}

	for _, file := range pkg.GoFiles {
		path := filepath.Join(dir, file)

		f, perr := parser.ParseFile(fset, path, nil, parser.PackageClauseOnly|parser.ParseComments)
		if perr != nil {
			return "", "", nil, perr
		}

		if f.Doc != nil {
			pkgDoc = f.Doc.Text()
		}
	}

	testFiles := slices.Concat(pkg.TestGoFiles, pkg.XTestGoFiles)

	for _, file := range testFiles {
		path := filepath.Join(dir, file)

		f, perr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if perr != nil {
			return "", "", nil, perr
		}

		tests = append(tests, f)
	}

	return pkg.Name, pkgDoc, tests, nil
}

// title returns the heading of ex, such as "stdout.NewHandler
// (withSourceAdded)".  A suffix is the part of the example name after the
// last underscore, if that part starts with a lowercase letter.
func title(pkg string, ex *doc.Example) string {
	symbol, suffix := ex.Name, ""

	i := strings.LastIndex(symbol, "_")
	if i >= 0 {
		first, _ := utf8.DecodeRuneInString(symbol[i+1:])
		if unicode.IsLower(first) {
			symbol, suffix = symbol[:i], symbol[i+1:]
		}
	}

	t := pkg
	if symbol != "" {
		t += "." + strings.ReplaceAll(symbol, "_", ".")
	}

	if suffix != "" {
		t += " (" + suffix + ")"
	}

	return t
}

// markdown returns the doc comment text as Markdown.
func markdown(text string) string {
	var p comment.Parser

	d := p.Parse(text)

	pr := comment.Printer{HeadingLevel: 4}

	return string(pr.Markdown(d))
}

// modulePath returns the module path in the go.mod file at path.
func modulePath(path string) (string, error) {
	b, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		return "", err
	}

	for line := range strings.Lines(string(b)) {
		module, ok := strings.CutPrefix(line, "module ")
		if ok {
			return strings.TrimSpace(module), nil
		}
	}

	return "", fmt.Errorf("%s: no module directive", path)
}

// compare returns an error if the file at path is different from text.
func compare(path string, text []byte) error {
	current, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		return err
	}

	if !bytes.Equal(current, text) {
		return fmt.Errorf("%s is out of date; run make docs", path)
	}

	return nil
}
